name: Setup initial kit name

on:
  workflow_dispatch:
    inputs:
      new_kit_name:
        description: "Set new name for kit. (my-awesome-kit)"
        required: true
  
jobs:
  rename:
    runs-on: ubuntu-latest
    # Only run on new repositories, not the template
    if: github.repository != 'Pixel-Fondue/modo-kit-basic'
    steps:
      - name: Chekout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Rename Kit
        run: |
          # Rename kit name in index.cfg
          sed -i 's/my_modo_kit/${{ github.event.inputs.newFolderName }}/g' my-modo-kit/index.cfg
          # Rename kit folder name
          mv my-modo-kit ${{ github.event.inputs.new_kit_name }}
      
      - name: Apply name changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Rename Modo kit" -a
      
      - name: Request Changes
        uses: repo-sync/pull-request@v2
        with:
          source_branch: 'gha/rename_branch'
          destination_branch: 'main'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: 'Rename kit to ${{ github.event.inputs.new_kit_name }}'
          pr_body: 'Automated changes by GitHub Action'
          
